BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "custom-display"
BBFILE_PATTERN_custom-display = "^${LAYERDIR}/"
BBFILE_PRIORITY_custom-display = "10" # Приоритет выше, чем у стандартных слоев
LAYERSERIES_COMPAT_custom-display = "mickledore"
